# Model arguments
model_name_or_path: model/GAI-LLM-Yi-Ko-6B-mixed-v15-sft-qlora-v4
torch_dtype: float16

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
train_data_path: data/dpo/GAI-LLM-Yi-Ko-6B-mixed-v15-qlora-v1-dpo-train.csv
eval_data_path: data/dpo/GAI-LLM-Yi-Ko-6B-mixed-v15-qlora-v1-dpo-eval.csv
preprocessing_num_workers: 8

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: GAI-LLM-Yi-Ko-6B-mixed-v15-sft-qlora
learning_rate: 5.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 512
max_prompt_length: 512
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: model/GAI-LLM-Yi-Ko-6B-mixed-v15-sft-qlora-dpo-v1 # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1