# Model arguments
model_name_or_path: skt/kogpt2-base-v2
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: false

# Data training arguments
train_data_path: data/train_v4.csv
eval_data_path: data/eval_v4.csv
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: kogpt2-base-v2-sft-full
hub_strategy: every_save
learning_rate: 1.0e-04
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 512
max_steps: -1
num_train_epochs: 4
output_dir: model/kogpt2-base-v2-sft-full-v4
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 32
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1